"""update events

Revision ID: 342be26712c7
Revises: f6e1e0046fc5
Create Date: 2020-12-18 23:40:30.622796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342be26712c7'
down_revision = 'f6e1e0046fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('type', sa.Enum('celebration', 'holiday', 'meeting', 'disco', 'culinary', 'other', name='eventtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'type')
    # ### end Alembic commands ###
